Audience: Different Organizations Tech and Non-Tech.
Argument: "Security breaches becomes more severe".
Chart Junk: Try to keep 1.
Data Source: https://docs.google.com/spreadsheets/d/1Je-YUdnhjQJO_13r8iTeRxpU2pBKuV6RVRHoYCgiMfg/edit#gid=322165570


Tableau Public: https://public.tableau.com/profile/nikhil.kaushik#!/vizhome/Work1_24/SecurityBreaches?publish=yes

In [4]:
#import extension libraries
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

Using the data source: Beautiful- Data Breaches (public).xlsx

In [6]:
wb_bty = pd.read_excel("Information is Beautiful- Data Breaches (public).xlsx")
sheet_1 = pd.read_excel("Information is Beautiful- Data Breaches (public).xlsx", sheetname= 0)
sheet_2 = pd.read_excel("Information is Beautiful- Data Breaches (public).xlsx", sheetname= 1)
sheet_3 = pd.read_excel("Information is Beautiful- Data Breaches (public).xlsx", sheetname= 2)

In [9]:
sheet_1.columns = map(str.upper, sheet_1.columns)

In [11]:
sheet_1 = sheet_1[1:254]

In [15]:
pd.options.mode.chained_assignment = None

Changing the data in the column YEAR to the correct year.

In [16]:
sheet_1.loc[sheet_1.YEAR==0,'YEAR']=2004
sheet_1.loc[sheet_1.YEAR==1,'YEAR']=2005
sheet_1.loc[sheet_1.YEAR==2,'YEAR']=2006
sheet_1.loc[sheet_1.YEAR==3,'YEAR']=2007
sheet_1.loc[sheet_1.YEAR==4,'YEAR']=2008
sheet_1.loc[sheet_1.YEAR==5,'YEAR']=2009
sheet_1.loc[sheet_1.YEAR==6,'YEAR']=2010
sheet_1.loc[sheet_1.YEAR==7,'YEAR']=2011
sheet_1.loc[sheet_1.YEAR==8,'YEAR']=2012
sheet_1.loc[sheet_1.YEAR==9,'YEAR']=2013
sheet_1.loc[sheet_1.YEAR==10,'YEAR']=2014
sheet_1.loc[sheet_1.YEAR==11,'YEAR']=2015
sheet_1.loc[sheet_1.YEAR==12,'YEAR']=2016
sheet_1.loc[sheet_1.YEAR==13,'YEAR']=2017
sheet_1.loc[sheet_1.YEAR==14,'YEAR']='Latest'

In [18]:
sheet_1.columns

Index(['ENTITY', 'ALTERNATIVE NAME', 'STORY', 'YEAR', 'RECORDS LOST',
       'ORGANISATION', 'METHOD OF LEAK', 'INTERESTING STORY',
       'NO OF RECORDS STOLEN', 'DATA SENSITIVITY', 'UNUSED', 'UNUSED.1',
       'EXCLUDE', 'UNNAMED: 13', '1ST SOURCE LINK', '2ND SOURCE LINK',
       '3RD SOURCE', 'SOURCE NAME'],
      dtype='object')

Wrangling data:
1. removed unwanted record
2. changed the values of years as per coded.
3. Made the header standard.

Deleting the Columns which might not help for the current argument

In [21]:
# Deleting the unwanted Columns
del sheet_1['ALTERNATIVE NAME']
del sheet_1['STORY']
del sheet_1['INTERESTING STORY']
del sheet_1['NO OF RECORDS STOLEN']
del sheet_1['UNUSED']
del sheet_1['UNUSED.1']
del sheet_1['EXCLUDE']
del sheet_1['UNNAMED: 13']
del sheet_1['1ST SOURCE LINK']
del sheet_1['2ND SOURCE LINK']
del sheet_1['3RD SOURCE']
del sheet_1['SOURCE NAME']

In [28]:
sheet_1.columns

Index(['ENTITY', 'YEAR', 'RECORDS LOST', 'ORGANISATION', 'METHOD OF LEAK',
       'DATA SENSITIVITY'],
      dtype='object')

In [ ]:
sheet_1.dtypes

Checking for distinct/Unique values in hte field DATA SESITIVITY for data wrangling.

In [33]:
sheet_1['DATA SENSITIVITY'].unique()

array([1, 20, 300, '20', 50000, 4000, '300', 3], dtype=object)

In [37]:
sheet_1.loc[sheet_1['DATA SENSITIVITY']==1,'DATA SENSITIVITY']='Just email address/Online information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==20,'DATA SENSITIVITY']='SSN/Personal details'
sheet_1.loc[sheet_1['DATA SENSITIVITY']=='20','DATA SENSITIVITY']='SSN/Personal details'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==300,'DATA SENSITIVITY']='Credit card information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']=='300','DATA SENSITIVITY']='Credit card information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==4000,'DATA SENSITIVITY']='Email password/Health records'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==50000,'DATA SENSITIVITY']='Full bank account details'

In [38]:
sheet_1['DATA SENSITIVITY'].unique()

array([1, 20, 300, 'SSN/Personal details', 50000, 4000,
       'Credit card information', 3], dtype=object)

In [39]:
sheet_1.loc[sheet_1['DATA SENSITIVITY']==1,'DATA SENSITIVITY']='Just email address/Online information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==20,'DATA SENSITIVITY']='SSN/Personal details'
sheet_1.loc[sheet_1['DATA SENSITIVITY']=='20','DATA SENSITIVITY']='SSN/Personal details'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==300,'DATA SENSITIVITY']='Credit card information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']=='300','DATA SENSITIVITY']='Credit card information'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==4000,'DATA SENSITIVITY']='Email password/Health records'
sheet_1.loc[sheet_1['DATA SENSITIVITY']==50000,'DATA SENSITIVITY']='Full bank account details'

In [40]:
sheet_1['DATA SENSITIVITY'].unique()

array(['Just email address/Online information', 'SSN/Personal details',
       'Credit card information', 'Full bank account details',
       'Email password/Health records', 3], dtype=object)

Correcting the value of DATA SENSITIVITY, where DATA SENSITIVITY is 3.

In [44]:
sheet_1.loc[sheet_1['DATA SENSITIVITY'] == 3]

ENTITY  YEAR RECORDS LOST ORGANISATION  \
134  South Carolina State Dept. of Revenue  2012      3600000   government   

    METHOD OF LEAK DATA SENSITIVITY  
134         hacked                3

In [45]:
sheet_1.loc[sheet_1['DATA SENSITIVITY']==3,'DATA SENSITIVITY']='Credit card information'

In [47]:
sheet_1.to_csv('Data_Assignment2.csv')

In [52]:
import numpy as np

Checking for NULLS in RECORDS LOST column.

In [53]:
np.where(sheet_1['RECORDS LOST'].isnull())[0]

array([146, 162])

In [55]:
sheet_1.iloc[146]

ENTITY                               OVH
YEAR                                2013
RECORDS LOST                         NaN
ORGANISATION                         web
METHOD OF LEAK                    hacked
DATA SENSITIVITY    SSN/Personal details
Name: 147, dtype: object

In [56]:
sheet_1 = sheet_1.dropna()

In [59]:
# 1. Removed Nulls

In [60]:
# 2. Corrected Data Sensitivity where Data Sensitivity was 3. Assuming it to be 300.

Changing the value of YEAR from LATEST to 2017.

In [61]:
sheet_1.loc[sheet_1.YEAR=='Latest','YEAR']= 2017

In [63]:
sheet_1.to_csv('Data_Assignment2.csv')

I have created 2 intermediated Tableau charts and 1 Final Chart.

Version 1: This version of visualization shows, number of Records Lost over the years.
Advantages/disadvantages and how the next version could improve it:
This graph helps in observing the change in number of Records Lost based on year. 
But this graph doesn’t provide information about the number of Incidents/breaches every year.

Version 2: This version shows the number of Incidents changing over the years and the number of Record Lost changing over the years.

Advantages/disadvantages and how the next version could improve it:
This version gives better understanding than the previous version. We can see the Number of breached/Incident happening in a year plus we can also see the number of Records lost versus year.

Final : 1.  The data source for this chart is “Information is Beautiful- Data Breaches (public).xlsx” 
2.  This chart supports the Argument that the data breaches have increased over the years. 
3.  This argument is supported by taking the Number of Record Lost over the years. 
4.  The data can be filtered on Organisation and Method Of Leak.
5.  The filters can be used to see the trend in the Number of Record Lost over the span of 13 years.